### ISSUE TITLE
1.21.1 - 1.21.3 support

### ISSUE THREAD

**Issue by GunnyWaffle** [Polymeta/serverlinkssender#1]
First of all, thank you for this mod. It's much appreciated.

Do you plan to provide a version for 1.21.1?

Thank you for your time!

**Comment by Polymeta** [comment]
Hi there, yes, I will, 1.21.1 is close to identical to 1.21, so I expect this to work without an issue or changes needed

**Comment by GunnyWaffle** [comment]
Yep, this should go very smoothly!
Thank you for the update.

**Comment by GunnyWaffle** [comment]
I'm re-opening this issue to check if this will be updated to 1.21.3

**Comment by Polymeta** [comment]
it should work out of the box

**Comment by GunnyWaffle** [comment]
It does not work for 1.21.1, 1.21.2, or 1.21.3.
Here is the error:
```
[14:57:17] [main/WARN]: Mod resolution failed
[14:57:17] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED serverlinkssender 1.0 {depends minecraft @ [1.21]}, ROOT_FORCELOAD_SINGLE serverlinkssender 1.0]
[14:57:17] [main/INFO]: Reason: [HARD_DEP serverlinkssender 1.0 {depends minecraft @ [1.21]}]
[14:57:17] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-sound-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[14:57:17] [main/INFO]: Fix: add [], remove [], replace [[serverlinkssender 1.0] -> add:serverlinkssender 1 ([(-Γê₧,Γê₧)])]
[14:57:17] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'ServerLinksSender' (serverlinkssender) 1.0 with any version that is compatible with:
                 - minecraft 1.21.3
More details:
         - Mod 'ServerLinksSender' (serverlinkssender) 1.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
```

I assume that you just need to update the mod to not have a hard dependency on 1.21.

**Comment by Polymeta** [comment]
You are right, published a new version now
